[workspace]
resolver = "2"
members = [
  "crates/bndl_cli",
  "crates/bndl_convert",
  "crates/bndl_deps",
]

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1
