name: Publish binary crate

on:
  workflow_dispatch:
    inputs:
      crate:
        description: "Binary to publish"
        required: true
        type: choice
        options:
          - bndl_cli
          - bndl_convert

concurrency:
  group: publish-${{ inputs.crate }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          toolchain: stable
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        working-directory: crates/${{ inputs.crate }}

  deps:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
      binary_name: ${{ steps.binary.outputs.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          toolchain: stable
      - name: Get current package version
        id: current_version
        run: echo "version=$(make version)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}
      - name: Get binary name
        id: binary
        run: echo "name=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select( .name == "${{ inputs.crate }}") | .targets[] | select( .kind | map(. == "bin") | any ) | .name')" >> $GITHUB_OUTPUT

  build:
    needs: [lint, deps]
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-unknown-linux-musl,
              exe: amd64-linux,
              os: ubuntu-latest,
            }
          - {
              target: aarch64-unknown-linux-musl,
              exe: aarch64-linux,
              os: ubuntu-latest,
            }
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.job.target }} --locked --package ${{ inputs.crate }}
          command: build
      - name: Rename result
        run: cp target/${{ matrix.job.target }}/release/${{ needs.deps.outputs.binary_name }} ${{ needs.deps.outputs.binary_name }}-${{ matrix.job.exe }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ${{ needs.deps.outputs.binary_name }}-${{ matrix.job.exe }}

  release:
    needs: [deps, build]
    environment: production
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_tag.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: crates/${{ inputs.crate }}/bin
      - uses: mukunku/tag-exists-action@v1.4.0
        id: check_tag
        with:
          tag: "${{ needs.deps.outputs.current_version }}"
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   if: steps.check_tag.outputs.exists == 'false' && inputs.crate == 'bndl_cli'
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "${{ needs.deps.outputs.current_version }}"
      #     prerelease: false
      #     files: |
      #       ./crates/${{ inputs.crate }}/bin/${{ needs.deps.outputs.binary_name }}-macos
      #       ./crates/${{ inputs.crate }}/bin/${{ needs.deps.outputs.binary_name }}-aarch64-linux
      #       ./crates/${{ inputs.crate }}/bin/${{ needs.deps.outputs.binary_name }}-amd64-linux

  cargo:
    needs: release
    environment: production
    runs-on: ubuntu-latest
    if: inputs.crate != 'bndl_cli' || (inputs.crate == 'bndl_cli' && needs.release.outputs.tag_exists == 'false')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        working-directory: crates/${{ inputs.crate }}
      - name: Publish to Cargo
        run: cargo publish --allow-dirty --package ${{ inputs.crate }} --dry-run || true
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  npm:
    needs: [deps, release, cargo]
    environment: production
    runs-on: ubuntu-latest
    if: inputs.crate != 'bndl_cli' || (inputs.crate == 'bndl_cli' && needs.release.outputs.tag_exists == 'false')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: crates/${{ inputs.crate }}/bin
      - name: Ensure run script is in place
        run: cp -R scripts crates/${{ inputs.crate }}/scripts
      - name: Ensure run script points to correct binary
        run: sed -i 's/__REPLACE__/${{ needs.deps.outputs.binary_name }}/' crates/${{ needs.deps.outputs.binary_name }}/scripts/run.sh
      - name: Publish to NPM
        run: |
          npm version ${{ needs.lint.outputs.current_version }} --no-git-tag-version --no-commit-hooks --allow-same-version
          npm publish --dry-run || true
        working-directory: crates/${{ inputs.crate }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
