on:
  workflow_dispatch:
    inputs:
      crate:
        description: "Binary to publish"
        required: true
        type: choice
        options:
          - bndl
          - bndl-convert

concurrency:
  group: publish-${{ inputs.crate }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
      package_name: ${{ steps.package_name.outputs.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          toolchain: nightly
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Get current package name
        id: package_name
        run: echo "name=$(make name)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}
      - name: Get current package version
        id: current_version
        run: echo "version=$(make version)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}

  build:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-unknown-linux-musl,
              exe: amd64-linux,
              os: ubuntu-latest,
            }
          - {
              target: aarch64-unknown-linux-musl,
              exe: aarch64-linux,
              os: ubuntu-latest,
            }
          - { target: x86_64-apple-darwin, exe: macos, os: macos-latest }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          args: --release --target=${{ matrix.job.target }} --locked --package ${{ needs.lint.outputs.package_name }}
          command: build
      - name: Rename result
        run: |
          rm target/${{ matrix.job.target }}/release/${{ inputs.crate }}.d
          cp target/${{ matrix.job.target }}/release/${{ inputs.crate }} ${{ inputs.crate }}-${{ matrix.job.exe }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: ${{ inputs.crate }}-${{ matrix.job.exe }}

  release:
    needs: [lint, build]
    environment: production
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_tag.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: crates/${{ inputs.crate }}/bin
      - uses: mukunku/tag-exists-action@v1.4.0
        id: check_tag
        with:
          tag: "${{ needs.lint.outputs.current_version }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.check_tag.outputs.exists == 'false' && inputs.crate == 'bndl'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.current_version.outputs.version }}"
          prerelease: false
          files: |
            ./crates/${{ inputs.crate }}/bin/${{ inputs.crate }}-macos
            ./crates/${{ inputs.crate }}/bin/${{ inputs.crate }}-aarch64-linux
            ./crates/${{ inputs.crate }}/bin/${{ inputs.crate }}-amd64-linux

  cargo:
    needs: release
    environment: production
    runs-on: ubuntu-latest
    if: inputs.crate != 'bndl' || (inputs.crate == 'bndl' && needs.release.outputs.tag_exists == 'false')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Get current package name
        id: package_name
        run: echo "name=$(make name)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}
      - name: Publish to Cargo
        run: cargo publish --allow-dirty --package ${{ steps.package_name.outputs.name }} || true
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  npm:
    needs: [lint, release, cargo]
    environment: production
    runs-on: ubuntu-latest
    if: inputs.crate != 'bndl' || (inputs.crate == 'bndl' && needs.release.outputs.tag_exists == 'false')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: crates/${{ inputs.crate }}/bin
      - name: Ensure preinstall script is in place
        run: cp -R scripts crates/${{ inputs.crate }}/scripts
      - name: Publish to NPM
        run: |
          npm version ${{ needs.lint.outputs.current_version }} --no-git-tag-version --no-commit-hooks --allow-same-version
          npm publish || true
        working-directory: crates/${{ inputs.crate }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
