name: Publish library crate

on:
  workflow_dispatch:
    inputs:
      crate:
        description: "Library to publish"
        required: true
        type: choice
        options:
          - bndl-deps

concurrency:
  group: publish-${{ inputs.crate }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
      package_name: ${{ steps.package_name.outputs.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          toolchain: nightly
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Get current package name
        id: package_name
        run: echo "name=$(make name)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}
      - name: Get current package version
        id: current_version
        run: echo "version=$(make version)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}

  cargo:
    needs: lint
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Get current package name
        id: package_name
        run: echo "name=$(make name)" >> $GITHUB_OUTPUT
        working-directory: crates/${{ inputs.crate }}
      - name: Publish to Cargo
        run: cargo publish --allow-dirty --package ${{ needs.lint.outputs.package_name }} || true
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
